language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: Dqo/HSU1dGVjYKdEisUhUjq0+HDB2rApG3HxaJGx1FcdhSUPcNHKmpJkwxJWJADQc2biIPiKD0bNtPcyT/xfinMr3Qafw5SYW59zE4wWPCLfUk+CHOs2MF1pt7PpR0grjuUydTCIO2Jv6NUID0VwNbzCji25W9Zmm9Ih6H8fHW0cUl8zoukhWZQldfPfOnj5wbwArOE0iYdQPZQNjOa5D4YKUBjuYZQbLteu9Kkq7B+KtedATHaR9r+GQSYaxIeLYEWGeW35FBOJovDgsMPXMgJ26OPkhMSohtgT7zaLydisH4elz4CWTUnm3PumTLA68Tk8KpfKmARyqwhoCuPawvCZI5eRahHegXZoGUfILmSKlSwqZVh9vPMMBu4hw7pKL8doeTgllqmfXp7pHUb1WfvfeZ0dkJlPU50YQ/B3yF+x8NF+LkP/DzwArIQnbW+rtkAnQirc7UkhMnlacCwmMBklew9/z39KLuHRfckr+7GKAWGnkfLv+nB0tHruVgcUj42PiO2AfUt8MJU9T4J/vNYfTjou7M9+WAs+Vn5o2mlhOQ2Gm+sXsGYDo4KgBr8KeayapfgJuIOyv7Q86V0rQgxOeYYVQaPhepB8MY6OfDiC986Nj4HNNCd9F87W0PQ0Sp37tfT4geM/zhT/VkcAUEDGEZYRzAHKEotzAtXlNHY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: SpheMakh/msutils
